{
 "title": "Canary",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Web Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_rq_xx{pod=~\"web.*\", local_cluster=\"web\", envoy_http_conn_manager_prefix=\"upstream\", envoy_response_code_class=~\"2|5\"}[30s])",
     "legendFormat": "Response Code {{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Retries per Second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry{consul_source_service=\"web\"}[30s]))"
    }
   ]
  },
  {
   "title": "API Request per Second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (envoy_response_code) (rate(envoy_cluster_upstream_rq{pod!~\"api-primary.*\", namespace=\"default\", envoy_cluster_name=\"local_app\"}[30s]))",
     "legendFormat": "Canary - {{envoy_response_code}}"
    },
    {
     "expr": "sum by (envoy_response_code) (rate(envoy_cluster_upstream_rq{pod=~\"api-primary.*\", namespace=\"default\", envoy_cluster_name=\"local_app\"}[30s]))",
     "legendFormat": "Primary - {{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Running Instances",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{pod=~\"api-primary.*\", pod=~\"api.*\"})",
     "legendFormat": "Primary"
    },
    {
     "expr": "sum(kube_pod_status_ready{pod!~\"api-primary.*\", pod=~\"api.*\"})",
     "legendFormat": "Canary"
    }
   ]
  },
  {
   "title": "SMI Controller Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{app=\"smi-controller\"} |= \"TrafficSplit\""
    }
   ]
  }
 ]
}